version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  web: #name of the second service
    build: # specify the directory of the Dockerfile
      context: ./web
      dockerfile: Dockerfile.web
    volumes:
      - ./web/frontend/dist:/web/html
      - ./web/api:/web/html/api
    ports:
      - 9000:80
    depends_on:
      - db
    links:
      - "db:database"
    env_file:
     - ./web/environment.env

  db:
    build:
      context: ./database
      dockerfile: Dockerfile.db
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose: 
      - 5432
    ports:
      - 5432:5432
    
  # database: # name of the third service
  #   image: mongo # specify image to build container from
  #   ports:
  #     - "27017:27017" # specify port forewarding